// Generated by scripts/prepare-project-images.mjs. Keep original lighting samples.
import { publicAssetUrl } from '../lib/public-asset.ts';

export const projectArtwork = [
  { image: publicAssetUrl('/images/projects/posters/01-karakter-studyo.1536.jpg'), sourceWidth: 1672, sourceHeight: 941, averageColor: [0.5119485294117647,0.48083639705882353,0.42443321078431373] },
  { image: publicAssetUrl('/images/projects/posters/02-kipir.1536.jpg'), sourceWidth: 1672, sourceHeight: 941, averageColor: [0.7339001225490196,0.46890318627450983,0.41574754901960786] },
  { image: publicAssetUrl('/images/projects/posters/03-snow-medya.1536.jpg'), sourceWidth: 1672, sourceHeight: 941, averageColor: [0.625827205882353,0.6218290441176471,0.6253676470588235] },
  { image: publicAssetUrl('/images/projects/posters/04-ezo-eylul-sagir.1536.jpg'), sourceWidth: 1672, sourceHeight: 941, averageColor: [0.45876225490196076,0.3569087009803922,0.26142769607843136] },
  { image: publicAssetUrl('/images/projects/posters/05-vanta-drive.1536.jpg'), sourceWidth: 1672, sourceHeight: 940, averageColor: [0.2778799019607843,0.2972886029411765,0.31953125] },
  { image: publicAssetUrl('/images/projects/posters/06-kome.1536.jpg'), sourceWidth: 1672, sourceHeight: 941, averageColor: [0.6310355392156862,0.48829656862745097,0.10893075980392157] },
  { image: publicAssetUrl('/images/projects/posters/07-dijital-ajans.1536.jpg'), sourceWidth: 1672, sourceHeight: 941, averageColor: [0.1770986519607843,0.21127450980392157,0.16182598039215687] },
] as const;
